CREATE TABLE MyTable(
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    val NUMBER
);
COMMIT;

SELECT * FROM MYTABLE FETCH FIRST 50 ROWS ONLY;
TRUNCATE table MyTable;
DROP TABLE MyTable;
-- UPDATE MYTABLE
--     SET val = 
