-- ALTER SESSION SET CURRENT_SCHEMA = KIRILL;

CREATE OR REPLACE TRIGGER cascade_delete_students
BEFORE DELETE ON GROUPS
FOR EACH ROW
BEGIN
    DELETE FROM STUDENTS WHERE group_id = :OLD.group_id;
END;
/
DELETE FROM GROUPS WHERE name = '253505';


SELECT * FROM STUDENTS;
SELECT * FROM GROUPS;
COMMIT;
