-- CREATE USER KIRILL IDENTIFIED BY 1234;
-- GRANT ALL PRIVILEGES TO KIRILL;

-- -- Switch to the new user
-- ALTER SESSION SET CURRENT_SCHEMA = KIRILL;

CREATE TABLE GROUPS(
    group_id NUMBER,
    name VARCHAR2(128),
    c_val NUMBER
);


CREATE TABLE STUDENTS(
    student_id NUMBER ,
    name VARCHAR2(128),
    group_id NUMBER
);

-- DROP TABLE GROUPS;
-- DROP TABLE STUDENTS;

