-- ALTER SESSION SET CURRENT_SCHEMA = KIRILL;
CREATE TABLE TEMP_GROUPS (
    group_id NUMBER
);
SELECT * FROM TEMP_GROUPS;

CREATE OR REPLACE TRIGGER TRACK_GROUP_CHANGES
AFTER INSERT OR UPDATE OR DELETE ON STUDENTS
FOR EACH ROW
BEGIN
    IF DELETING OR UPDATING THEN
        INSERT INTO TEMP_GROUPS (group_id)
        SELECT :OLD.group_id FROM DUAL
        WHERE :OLD.group_id IS NOT NULL;
    END IF;

    IF INSERTING OR UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('INSERTING');
        INSERT INTO TEMP_GROUPS (group_id) VALUES (:NEW.group_id);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER update_student_count_in_group
AFTER INSERT OR UPDATE OR DELETE ON STUDENTS
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    FOR r IN (SELECT DISTINCT group_id FROM TEMP_GROUPS) LOOP
        UPDATE GROUPS
        SET c_val = (SELECT COUNT(*) FROM STUDENTS WHERE group_id = r.group_id)
        WHERE group_id = r.group_id;
    END LOOP;
    COMMIT;
END;
/
-- DROP TABLE TEMP_GROUPS;
COMMIT;